kind: pipeline
name : neXus Lavender
version: rev1.5_template
steps:
 - name: neXus Lavender
   image: xyzuan/xdocker:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
     - git clone --depth=1 --single-branch -b eas-beta https://github.com/NotZeetaa/nexus_kernel_lavender lavender
     - cd lavender
     - bash build.sh
